[SNOWFLAKE]
USER="devrag"
PASSWORD="Bsdb@123"
ACCOUNT="pdhifjj-sxb83619"
DATABASE="DEVRAG_DB"
SCHEMA="DEVRAG_SCHEMA"
WAREHOUSE="DEVRAG"

[FIREBASE]
TYPE="service_account"
PROJECT_ID="devrag-e191a"
PRIVATE_KEY_ID="d180030348a95dbf9e7b9403e2ce75361fb59985"
PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfDJZEBvLDoE0P\nSq75uEvr9RTrPcNYnF/u2NWhnjM/YEYB+nWqC1mMoyLy9vdU8jlJCerpwMQC2xW3\nVwBOI1MiZXbWjxAzlb1uWdtLWrhONKFNaC04vDvzLjUv81j506RGkqAYi55FL6io\n3yBiJqM2d1HSMAcpq4i1/GaXAwjbtD23QMFYO02EGQuE8M/xP8Pnxu5J8mofghy7\n19tczMqoM7DHrx7Mmdvwn873lMNkEqSkLH22y4zrvPAUl84doCnyWknIMZMmbKDq\niil4/B845OzgcdZDoQw7Qc6bIxTfHPkssfzaaR7K0++qZZdekkt7V7SI1dnmVTCb\nWNQuQIMbAgMBAAECggEAGDQXp+mGHFayyLQc9YaMvdnGzFen+GjvlmQr+mjIiV6d\nY2QEb5NDljR7Nzh1rK53IOd1TAuC00vDaGpBHc2gCJjNNrCAZCvnhGQAjF1ACogA\nJfdHrnMYDRUykIX6kSYaa9zt/Qjo1cQqE+zEkPsqlOQf25m7H/sTwQdUa1WnDZve\nJvj4SRQ0WUuAJGyB6zVjCbobbF7lj5860X14wZcFh5WP10hlOsrZRdF1Qp1iUvRs\nr8KGDwEJ/QoCjmxES0f6vR0+6HaQI0GLW0EAVyLYOrHLtVgr6f/P6Y3y26tMbKmR\nopYXE4/uwOmsKl4EfHyDmFe95R/4mwbNMaCr4aW6FQKBgQDVl1Rw6ZfqF41vNvcM\nLue9HoookqMpsYVoJ3blwqmkbAq+Sn0R+QEubDqEg6i7O5wgUdtvo11JmLQX4yRs\n9DRveCkuySa2uRJaDcyMiSfVVXhAO7r4ZdYSUE5cxZ6z5ZlVhJeJfYwNBieHb+z3\nRSCz7d7yAsa8w99F/RDNd9PfZwKBgQC+oO6HJf7dlQvQvU+AtfWWrbmlxqa+7OZB\nVWJX7NbuXS0kSDepp3/hR0j0ZEpMUT16HQoszzRhPmNkr1gO2VpBhwW6j70XHpH3\nggE9U0Y4GDUntHlMKUICZoZF3Dihvy6OciZt9s7iLp+oAHAORSY1fzVSVSv8QdJi\nCTeSfisSLQKBgCFmMIYXgPHSDQO/DJKTIxmnlOMTSwBSChJnWWhEMFLNskBfVX9h\n+JVRxzTBgbkFcTx8kFu8p/HCNyclFaUT6r8jgw0V1z/rYLtEPSAcsmXhn5Qrwujk\nw7zJYfePz2lCFeARg8C0KRpARB4hmmRwItT/9UTSulD6MAe5ss7uVesxAoGBAKhz\nHVRfxu+XHXG/V9ms8O/NZBeRixd7z5w8D0MTDnpj69f72PQaB27Sxyzu0pjN0T1v\nG+as0uR7dOkr6Ox2NMNixTUufzFG2kWUo/PE+m/nNFF5sRYT/ziP0Gc7Su/jOQi2\n5i6Vwgssl/ilKl/xyunLFxtCGDQ5Fed7rZfN1dGhAoGAcmHVfcJSvdiURhF9cfRP\nEU9siVeAch9YwaMRA0Q25yIBsgcPNVLjH7yijztz/fueRxKHDQhQZw2FuOyTb6pJ\nBtS26Z275fjM8621tmKlwtOvoGyofl0JI+TLA+Q6Nj4T9OZh0W7k4/KGm5+biWBb\n7tZnULfTAuJy+St859K368E=\n-----END PRIVATE KEY-----\n"
CLIENT_EMAIL="firebase-adminsdk-dv2k5@devrag-e191a.iam.gserviceaccount.com"
CLIENT_ID="113389490966378920603"
AUTH_URI="https://accounts.google.com/o/oauth2/auth"
TOKEN_URI="https://oauth2.googleapis.com/token"
AUTH_PROVIDER_X509_CERT_URL="https://www.googleapis.com/oauth2/v1/certs"
CLIENT_X509_CERT_URL="https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-dv2k5%40devrag-e191a.iam.gserviceaccount.com"
UNIVERSE_DOMAIN="googleapis.com"
API_KEY="AIzaSyAAUeRx6Ts_0Tf92q0FpA1t4In4a05Elwk"
AUTH_DOMAIN="devrag-e191a.firebaseapp.com"
DATABASE_URL="https://devrag-e191a-default-rtdb.firebaseio.com"
PROJECT_ID="devrag-e191a"
STORAGE_BUCKET="devrag-e191a.firebasestorage.app"
MESSAGING_SENDER_ID="454521015058"
APP_ID="1:454521015058:web:641e9db5ad644ee7cc01cb"

[MISTRAL]
API_KEY="1t8YR25vJ1WIi1erc4jlhxVoklwAezjj"